Repository c4deszes/ldfparser, pull requests merged in 2021-06, with the labels that each got.

#52 Cleans up CI workflows
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  README.md
Labels: ci, enhancement

#50 Performance testing
  .github/workflows/build.yml
  .gitignore
  pytest.ini
  requirements.txt
  tests/test_cli.py
  tests/test_performance.py
Labels: ci, enhancement

#55 Disables automatic changelog and asset upload
  .github/workflows/release.yml
Labels: bug, ci, priority:high

#56 Fixes missing encoding types `ascii_value` and `bcd_value`.
  ldfparser/ldf.lark
  schemas/ldf.json
  tests/ldf/lin_encoders.ldf
  tests/test_parser.py
Labels: bug, ldf/encoding, parser
